<a href="https://colab.research.google.com/github/Shindora/NLP-with-PyTorch/blob/master/Chapter_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PyTorch basic**<br>


In [0]:
def describe(x):
  print('Type: {}'.format(x.type()))
  print('Shape/Size: {}'.format(x.shape))
  print('Values: \n{}'.format(x))

In [0]:
import torch
describe(torch.Tensor(2,3))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[6.3088e-35, 0.0000e+00, 1.5695e-43],
        [1.5554e-43, 1.5975e-43, 1.6255e-43]])


In [0]:
describe(torch.rand(2,3))
describe(torch.rand(2,3))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0.4737, 0.5769, 0.1901],
        [0.3811, 0.6308, 0.2481]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0.2954, 0.1330, 0.6195],
        [0.9833, 0.1581, 0.8410]])


We can also create tensors all filled with the same scalar. For creating a tensor of zeros or ones, we
have built­in functions, and for filling it with specific values, we can use the fill_() method. Any
PyTorch method with an underscore (_) refers to an in­place operation

In [0]:
describe(torch.zeros(2,3))
x=torch.ones(2,3)
describe(x)
x.fill_(5)
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [0]:
x=torch.Tensor([[1,2,3],
         [4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


From Numpy to Torch

In [0]:
import numpy as np
npy=np.random.rand(2,3)
describe(torch.from_numpy(npy))

Type: torch.DoubleTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0.4414, 0.7820, 0.8833],
        [0.0443, 0.5173, 0.3456]], dtype=torch.float64)


Tensor Types and Size

In [0]:
x=torch.FloatTensor([[1,2,3],[4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [0]:
x=x.long()
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


Tensor Operations

In [0]:
x=torch.randn(2,3)
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[ 0.6917, -1.0968, -0.0889],
        [-0.6318,  1.3909, -0.1471]])


In [0]:
describe(torch.add(x,x))
describe(x+x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[ 1.3833, -2.1936, -0.1777],
        [-1.2637,  2.7817, -0.2943]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[ 1.3833, -2.1936, -0.1777],
        [-1.2637,  2.7817, -0.2943]])


In [0]:
x=torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [0]:
x=x.view(3,2)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [0]:
describe(torch.sum(x,dim=0))
describe(torch.sum(x,dim=1))

Type: torch.LongTensor
Shape/Size: torch.Size([2])
Values: 
tensor([6, 9])
Type: torch.LongTensor
Shape/Size: torch.Size([3])
Values: 
tensor([1, 5, 9])


In [0]:
describe(torch.transpose(x,1,0))

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 2, 4],
        [1, 3, 5]])


In [0]:
describe(torch.transpose(x,0,1))

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 2, 4],
        [1, 3, 5]])


Index, Slicing, Joining

In [0]:
x=torch.arange(6).view(2,3)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [0]:
describe(x[:1,:2])

Type: torch.LongTensor
Shape/Size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])


In [0]:
describe(x[0,1])

Type: torch.LongTensor
Shape/Size: torch.Size([])
Values: 
1


In [0]:
describe(torch.cat([x,x],dim=0))

Type: torch.LongTensor
Shape/Size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [0]:
describe(torch.cat([x,x],dim=1))

Type: torch.LongTensor
Shape/Size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [0]:
describe(torch.stack([x,x]))

Type: torch.LongTensor
Shape/Size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [0]:
x2=torch.arange(6).view(2,3)
x2[:,1]+=1
describe(x2)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 2, 2],
        [3, 5, 5]])


In [0]:
x1=torch.arange(6).view(3,2)
describe(torch.mm(x1,x2))

Type: torch.LongTensor
Shape/Size: torch.Size([3, 3])
Values: 
tensor([[ 3,  5,  5],
        [ 9, 19, 19],
        [15, 33, 33]])


In [0]:
describe(x1@x2)

Type: torch.LongTensor
Shape/Size: torch.Size([3, 3])
Values: 
tensor([[ 3,  5,  5],
        [ 9, 19, 19],
        [15, 33, 33]])


**CUDA**

In [0]:
print(torch.cuda.is_available())

True


In [0]:
# preferred method: device agnostic tensor instantiation
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print (device)

cuda


In [0]:
x = torch.rand(3, 3).to(device)
describe(x)

Type: torch.cuda.FloatTensor
Shape/Size: torch.Size([3, 3])
Values: 
tensor([[8.5626e-01, 4.3414e-01, 8.6873e-01],
        [9.3752e-01, 5.4475e-01, 4.6378e-01],
        [1.4004e-01, 2.5790e-01, 7.1520e-04]], device='cuda:0')


In [0]:
y=torch.rand(3,3)
x+y

RuntimeError: ignored

In [0]:
cpu_device=torch.device("cpu")
y=y.to(cpu_device)
x=x.to(cpu_device)
x+y

tensor([[1.2940, 1.0368, 1.8420],
        [1.5547, 0.5777, 0.7419],
        [1.0198, 0.8726, 0.6602]])

**Exercises**

1. Create a 2d tensor and then add a dimension of size 1 inserted at dimension 0

In [0]:
a = torch.rand(3, 3)
describe(a)
a.unsqueeze(0)
describe(a)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 3])
Values: 
tensor([[0.5519, 0.8007, 0.3941],
        [0.3732, 0.9606, 0.7589],
        [0.0386, 0.9303, 0.2351]])
Type: torch.FloatTensor
Shape/Size: torch.Size([3, 3])
Values: 
tensor([[0.5519, 0.8007, 0.3941],
        [0.3732, 0.9606, 0.7589],
        [0.0386, 0.9303, 0.2351]])


2. Remove the extra dimension you just added to the previous tensor.

In [0]:
describe(a.squeeze(0))

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 3])
Values: 
tensor([[0.5519, 0.8007, 0.3941],
        [0.3732, 0.9606, 0.7589],
        [0.0386, 0.9303, 0.2351]])


3. Create a random tensor of shape 5x3 in the interval [3, 7)

In [0]:
x=3+torch.rand(5,3)*(7-3)
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([5, 3])
Values: 
tensor([[6.0520, 4.1812, 4.5421],
        [3.9850, 3.5141, 5.1405],
        [4.0205, 4.9051, 5.2141],
        [5.2217, 4.4695, 5.9333],
        [4.9425, 3.5723, 3.7571]])


4. Create a tensor with values from a normal distribution (mean=0, std=1)

In [0]:
x=torch.Tensor(2,3)
describe(x.normal_())

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[ 0.4685,  0.1592,  1.0724],
        [ 0.2237,  0.7683, -0.0731]])


In [0]:
describe(torch.randn(2,3))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[-0.6718, -1.0929, -0.2001],
        [-0.6578, -0.1122, -0.1570]])


5. Retrieve the indexes of all the nonzero elements in the tensor torch.Tensor([1, 1, 1,
0, 1])

In [0]:
a=torch.tensor([1,1,1,0,1])
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

6. Create a random tensor of size (3,1) and then horizontally stack four copies together

In [0]:
a=np.array([[1,2,3]])
a=np.hstack((a,a,a,a))
describe(torch.from_numpy(a))

Type: torch.LongTensor
Shape/Size: torch.Size([1, 12])
Values: 
tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])


7. Return the batch matrix­matrix product of two three­dimensional matrices
(a=torch.rand(3,4,5), b=torch.rand(3,5,4)).

In [0]:
a=torch.rand(3,4,5)
b=torch.rand(3,5,4)
describe(a@b)
describe(torch.bmm(a,b))

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 4, 4])
Values: 
tensor([[[0.5229, 0.9157, 0.4344, 0.6779],
         [1.1079, 1.2795, 0.5759, 0.9853],
         [0.8630, 1.3937, 0.5615, 0.9071],
         [0.9174, 2.2224, 1.0464, 1.7242]],

        [[1.3841, 0.7388, 1.2408, 1.0863],
         [0.7155, 0.7057, 0.9249, 0.8563],
         [1.2220, 0.8343, 1.2222, 1.0115],
         [1.3040, 0.8404, 1.1953, 1.0204]],

        [[0.9824, 0.5057, 0.5347, 0.4605],
         [1.3516, 0.9414, 0.6674, 0.7247],
         [2.1070, 1.2264, 1.4220, 0.9821],
         [2.1738, 1.0348, 1.9512, 1.2613]]])
Type: torch.FloatTensor
Shape/Size: torch.Size([3, 4, 4])
Values: 
tensor([[[0.5229, 0.9157, 0.4344, 0.6779],
         [1.1079, 1.2795, 0.5759, 0.9853],
         [0.8630, 1.3937, 0.5615, 0.9071],
         [0.9174, 2.2224, 1.0464, 1.7242]],

        [[1.3841, 0.7388, 1.2408, 1.0863],
         [0.7155, 0.7057, 0.9249, 0.8563],
         [1.2220, 0.8343, 1.2222, 1.0115],
         [1.3040, 0.8404, 1.1953, 1.0204]

8. Return the batch matrix­matrix product of a 3D matrix and a 2D matrix
(a=torch.rand(3,4,5), b=torch.rand(5,4)).

In [0]:
a=torch.rand(3,4,5)
b=torch.rand(5,4)
describe(a@b)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 4, 4])
Values: 
tensor([[[1.2628, 1.3793, 1.1576, 1.3146],
         [1.5373, 2.4409, 1.9342, 1.4653],
         [1.4306, 1.9148, 1.5586, 1.2936],
         [0.8554, 1.0929, 0.6541, 1.1433]],

        [[1.0893, 1.3279, 1.2650, 0.7141],
         [0.8341, 1.4919, 1.6073, 1.3789],
         [1.3449, 2.1005, 1.7131, 1.2840],
         [1.0747, 1.3083, 1.1396, 1.1322]],

        [[1.3787, 1.7067, 1.3171, 1.3737],
         [1.5710, 1.9860, 1.6829, 1.4464],
         [1.3955, 1.6990, 1.5919, 1.2175],
         [1.7736, 2.4288, 2.0306, 1.6366]]])


In [0]:
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))


tensor([[[1.2628, 1.3793, 1.1576, 1.3146],
         [1.5373, 2.4409, 1.9342, 1.4653],
         [1.4306, 1.9148, 1.5586, 1.2936],
         [0.8554, 1.0929, 0.6541, 1.1433]],

        [[1.0893, 1.3279, 1.2650, 0.7141],
         [0.8341, 1.4919, 1.6073, 1.3789],
         [1.3449, 2.1005, 1.7131, 1.2840],
         [1.0747, 1.3083, 1.1396, 1.1322]],

        [[1.3787, 1.7067, 1.3171, 1.3737],
         [1.5710, 1.9860, 1.6829, 1.4464],
         [1.3955, 1.6990, 1.5919, 1.2175],
         [1.7736, 2.4288, 2.0306, 1.6366]]])